// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package query

import (
	"database/sql"

	"github.com/google/uuid"
)

type Api struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	IsActive    sql.NullBool
	Description string
	CreatedBy   string
	CreatedAt   sql.NullTime
	UpdastedAt  sql.NullTime
}

type Client struct {
	ID                    uuid.UUID
	Name                  string
	Slug                  string
	Description           string
	ClientKey             string
	HashClientSecret      string
	RoundHashClientSecret int32
	SaltHashClientSecret  string
	IsActive              sql.NullBool
	LastLogin             sql.NullTime
	CreatedBy             string
	CreatedAt             sql.NullTime
	UpdastedAt            sql.NullTime
}

type ClientPermission struct {
	ID           uuid.UUID
	ClientID     uuid.UUID
	PermissionID uuid.UUID
	CreatedAt    sql.NullTime
}

type Permission struct {
	ID          uuid.UUID
	ApiID       uuid.UUID
	ApiResource string
	IsActive    sql.NullBool
	Action      sql.NullString
	CreatedAt   sql.NullTime
	UpdastedAt  sql.NullTime
}
