// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: query.sql

package query

import (
	"context"
)

const findAll = `-- name: FindAll :exec
SELECT id FROM apis
`

func (q *Queries) FindAll(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, findAll)
	return err
}
